import { NextRequest, NextResponse } from 'next/server'
import JSZip from 'jszip'
import { GeneratedFile } from '@/lib/types'

export async function POST(req: NextRequest) {
  const { files }: { files: GeneratedFile[] } = await req.json()

  const zip = new JSZip()

  // Add generated source files
  for (const file of files) {
    zip.file(file.path, file.content)
  }

  // Add package.json
  zip.file(
    'package.json',
    JSON.stringify(
      {
        name: 'my-dtc-site',
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint',
        },
        dependencies: {
          next: '^15.0.0',
          react: '^19.0.0',
          'react-dom': '^19.0.0',
          'framer-motion': '^11.0.0',
          'lucide-react': '^0.400.0',
        },
        devDependencies: {
          typescript: '^5',
          '@types/node': '^20',
          '@types/react': '^19',
          '@types/react-dom': '^19',
          tailwindcss: '^4',
        },
      },
      null,
      2
    )
  )

  // Add tsconfig
  zip.file(
    'tsconfig.json',
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2017',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [{ name: 'next' }],
          paths: { '@/*': ['./src/*'] },
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules'],
      },
      null,
      2
    )
  )

  // Add setup README
  zip.file(
    'README.md',
    `# My DTC Site

Generated by DTC Builder.

## 快速开始

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) to view the site.

## 部署到 Vercel

\`\`\`bash
npx vercel
\`\`\`
`
  )

  const arrayBuffer = await zip.generateAsync({ type: 'arraybuffer', compression: 'DEFLATE' })

  return new NextResponse(arrayBuffer, {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': 'attachment; filename="my-website.zip"',
    },
  })
}
