import { NextRequest, NextResponse } from 'next/server'
import { GeneratedFile } from '@/lib/types'

export async function POST(req: NextRequest) {
  const { files }: { files: GeneratedFile[] } = await req.json()

  // Build a simple ZIP-like archive as a text bundle
  // In production you'd use the 'archiver' or 'jszip' package
  // For now, return all files concatenated with clear separators
  const archive = buildTextArchive(files)

  return new NextResponse(archive, {
    headers: {
      'Content-Type': 'application/octet-stream',
      'Content-Disposition': 'attachment; filename="my-website.txt"',
    },
  })
}

function buildTextArchive(files: GeneratedFile[]): string {
  const separator = '='.repeat(60)

  const header = `# AI Generated Website
# Generated by DTC Builder
#
# 使用方法:
# 1. 创建新的 Next.js 项目: npx create-next-app@latest my-site --typescript --tailwind --app --src-dir
# 2. 将以下文件内容替换到对应路径
# 3. 安装依赖: npm install framer-motion lucide-react
# 4. 运行: npm run dev
#
${separator}

`

  const fileContents = files
    .map(
      (f) => `### FILE: ${f.path}\n${'─'.repeat(40)}\n${f.content}\n\n${separator}\n`
    )
    .join('\n')

  const packageJson = `
### FILE: package.json (merge with existing)
${'─'.repeat(40)}
{
  "dependencies": {
    "framer-motion": "^11.0.0",
    "lucide-react": "^0.400.0",
    "gsap": "^3.12.0"
  }
}

${separator}
`

  return header + fileContents + packageJson
}
